---
- hosts: localhost
  become: yes

  tasks:
  - name: update apt
    apt: upgrade=dist update_cache=yes
  - name: download docker installer
    get_url:
       url: https://get.docker.com
       dest: /tmp/install_docker.sh
       mode: 755
  - name: instll docker
    command: /tmp/install_docker.sh
    args:
       creates: /usr/bin/docker
  - name: install vnc
    apt: name=realvnc-vnc-server state=latest
  - name: install netatalk
    apt: name=netatalk state=latest
  - name: install avahi daemon
    apt: name=avahi-daemon state=latest
  - name: create afpd.service
    become: true
    blockinfile:
      dest: /etc/avahi/services/afpd.service
      create: yes
      block: |
        <?xml version="1.0" standalone='no'?><!--*-nxml-*-->
        <!DOCTYPE service-group SYSTEM "avahi-service.dtd">
        <service-group>
           <name replace-wildcards="yes">%h</name>
           <service>
              <type>_afpovertcp._tcp</type>
              <port>548</port>
           </service>
        </service-group>
  - name: create rfb.service
    become: true
    blockinfile:
      dest: /etc/avahi/services/rfb.service
      create: yes
      block: |
        <?xml version="1.0" standalone='no'?>
        <!DOCTYPE service-group SYSTEM "avahi-service.dtd">
        <service-group>
          <name replace-wildcards="yes">%h</name>
            <service>
            <type>_rfb._tcp</type>
            <port>5901</port>
          </service>
        </service-group>
  - name: restart avahi-daemon
    become: true
    service:
      name: avahi-daemon
      state: restarted
      enabled: yes

